### ISSUE TITLE
Create an faPerspective attribute directive requiring the faApp directive.

### ISSUE THREAD

**Issue by trusktr** [Famous/famous-angular#151]
In vanilla famo.us, perspective is something you apply to you famous context.

``` javascript
    var mainContext = Engine.createContext();
    mainContext.setPerspective(1200);
```

It would seem appropriate to make an `faPerspective` attribute directive for use on the 'faApp' directive like so:

``` html
<fa-app fa-perspective="1200" class="full-screen">
    ...
</fa-app>
```

**Comment by thiswildorchid** [comment]
This doesn't seem to work anymore

**Comment by jd-carroll** [comment]
Can you please provide more details as how this is not working...

@zackbrown This should be moved to `parseInt(scope.$eval(attrs.faPerspective))` or something similar.

**Comment by rohanrehman** [comment]
```html
<fa-app ng-controller="famousCtrl" style="width: auto; height: 800px" fa-perspective="1000">
```

@zackbrown setting a rotation 
```javascript
   $scope.box.rotate.set(-45 * Math.PI/180, {duration: 1200, curve: Easing.inOutExpo});
```

and an fa-modifier

```javascript
  fa-rotate-y="box.rotate.get()"
```

the box will rotate with no perspective applied until chrome (Version 41.0.2272.118 (64-bit)) is resized, resizing chrome before the animation is called makes no difference.

Bug is not reproduced in Safari.
