### ISSUE TITLE
Flexible Layout

### ISSUE THREAD

**Issue by Miggz** [Famous/famous-angular#183]
I am trying to implement a flexible-layout.  The documentation does not show a full example, except to show: 
```
<fa-flexible-layout fa-options="scopeOptionsObject">
</fa-flexible-layout>
```
Do I just add layout elements within the fa-flexible-layout element?  

For example: 
```
<fa-flexible-layout fa-options="scopeOptionsObject">
   <fa-surface>Content</fa-surface>
   <fa-surface>Content</fa-surface>
</fa-flexible-layout>
```

I have added options in my controller, but it doesn't seem to be working.  Any help would be most appreciated.  Also, I apologize if this is a stupid question, I'm more of a designer than a programmer.

Thanks

**Comment by jordanpapaleo** [comment]
@Miggz Is this still a valid issue? Thanks - Jordan
