### ISSUE TITLE
fa-translate breaks the rendering of surfaces when z is set to anything but 0

### ISSUE THREAD

**Issue by steveblue** [Famous/famous-angular#186]
If we translate on the z with `fa-translate`, surfaces get deployed but are not painted in the window. 

In the latest build, if we comment out `transform-style:preserve-3d` on the .famous-angular-container but leave it elsewhere in the css this bug is fixed and 3D transformations still work.

This may be a chrome specific bug.

**Comment by jordanpapaleo** [comment]
@steveblue Is this still a valid issue?  Thanks - Jordan

**Comment by steveblue** [comment]
Oh, yeah still an issue, please reopen. A lot of people have been able to reproduce.

**Comment by steveblue** [comment]
Please read my comment from before that seems to fix this bug.
