### ISSUE TITLE
$scope.apply does not update my view with new Model.

### ISSUE THREAD

**Issue by elinfante** [Famous/famous-angular#216]
Hi, 

I have a setTimeout interval to keep loading different config files. That runs every second. It looks like this: 

```
Timer.setTimeout (_loadMainConfig, s*1000);
```

The problem comes when in another Controller I update the $scope correctly (I can console log the values) but the view does not get updated until a new setTimeout is called (every second). Why is it doing that, I am banging my head against the wall!

I have tried using $scope.apply but that does not seem to solve the problem.

Thanks!

**Comment by jordanpapaleo** [comment]
Hi @elinfante,  Is this still a valid issue?  Thanks - Jordan
