### ISSUE TITLE
Should add annotation lib version in release section, please

### ISSUE THREAD

**Issue by nvcken** [Famous/famous-angular#230]
Just example 
0.4.1
famo.us : Upgrade to 0.3
angular : Upgrade to 1.2.26
...
0.4.0
famo.us : 0.2.2
angular : 1.2.22
....
ref https://github.com/joyent/node/releases

**Comment by jordanpapaleo** [comment]
Hi @nvcken -

Thank you for your suggestion.

So to clarify you would like this project to change the way it does its' versioning documentation.  I am not sure if that will happen but I can look into it.  First, could you please be a little more specific with your suggestion.  I would like an example of what we currently do, what you would like it to be, and why your suggestion will be helpful to this project and the community.

Thank you,

Jordan

**Comment by nvcken** [comment]
Hi
With currently Release section has only Version text, example 0.5.0. Then we should know how it new update feature , we need to reed changelog.md or bower.json to see what's change. So when we simple note little description on release section below Version text about version of
example 
famo.us : 0.3.0
angular : 1.2.26
May be It 's my behavior for quick see.
Thanks for help

**Comment by jordanpapaleo** [comment]
We appreciate the suggestion but we are going to continue using the change log for tracking updates to the project.  

Thanks,

Jordan
