### ISSUE TITLE
Scrollview and touch

### ISSUE THREAD

**Issue by pasine** [Famous/famous-angular#231]
I setup a view with a scrollview following the examples in the documentation.
It works fine on desktop, but it fails on: 
- Safari and Chrome on an iPad iOS8
- Chrome and Firefox on Android 4.4.4

I checked the [documentation website](http://famo.us/integrations/angular/docs/api/index.html) on both devices and it is not working either (the scrollview is not scrolling).
By the way, editing an example in plunkr and visiting it, works on both devices.
I have noticed that the website and the edited plunkr are using different versions of famo.us and angular-famous.
Can someone point me out where the problem could be?

**Comment by jordanpapaleo** [comment]
Thank you for stepping in and helping here @steveblue. 

@pasine are you still having issues?

**Comment by pasine** [comment]
No. Sorry, I forgot to close the issue. I'll do it now.
Thanks.

**Comment by jordanpapaleo** [comment]
Thanks for supporting and contributing to this project.
