### ISSUE TITLE
fa-view with fa-sequential layout breaks when view has more than one surface.

### ISSUE THREAD

**Issue by DrClick** [Famous/famous-angular#236]
the following works as expected
```
<fa-sequential-layout fa-options="sequentialOptions">
                                    <fa-view ng-repeat="item in risk.labs">
                                        <fa-surface class="labs" ng-class="{external: item.external}"
                                                    fa-size="[605, 36]">
                                            <span class="dot" ng-class="{filled: item.strength >= 3}"></span>
                                            <span class="dot" ng-class="{filled: item.strength >= 2}"></span>
                                            <span class="dot" ng-class="{filled: item.strength >= 1}"></span>
                                            &nbsp;
                                            <span class="date">({{item.date}})</span>&nbsp;<span class="name">{{item.name}}</span>
                                            <span class="value">{{item.value}}</span>
                                        </fa-surface>
                                        <!--NOTE THIS WORKS BUT ADDING A NEW SURFACE HERE KILLS IT-->
                                    </fa-view>
                                </fa-sequential-layout>
```

But as soon as I add something else, the surfaces collapse on each other (just replace the commented section above with a <fa-surface>Hello World</fa-surface>

Working
![screen shot 2014-10-15 at 5 58 48 pm](https://cloud.githubusercontent.com/assets/2525709/4656079/a0077880-54cf-11e4-89c3-eed2f1c848ea.png)

Failing (just try adding anything here such as <fa-surface>Hello World</fa-surface>
![screen shot 2014-10-15 at 5 59 22 pm](https://cloud.githubusercontent.com/assets/2525709/4656084/b75b7cd4-54cf-11e4-9a12-a3a58ee60ebc.png)

**Comment by jordanpapaleo** [comment]
Hi @DrClick  - 

Were you able to implement @imheresamir suggestion?

Thanks,

Jordan

**Comment by DrClick** [comment]
To be honest, I was in a motorcycle accident shortly after this and it was redone a different way. I vote close this issue.

**Comment by jordanpapaleo** [comment]
I hope you are ok.  Thank you for the update.  I will close this.

Thanks,

Jordan
