### ISSUE TITLE
3D Perspective wrong in a carrousel

### ISSUE THREAD

**Issue by elinfante** [Famous/famous-angular#237]
I have created a carrousel and when I click on each thumb It should rotate from the center. I got that bit working fine but for some reason the perspective is wrong, is not head on therefore they all look different when they should be the same.

I am a bit confused why is doing that, any ideas?

This is the directive:

```
	<fa-modifier 	bz-carrousel-thumb
					ng-repeat="photo in photos"
					fa-animate-enter="enter()"
					fa-animate-leave="leave()"
					fa-animate-halt="halt()"
					fa-transform="transform"
					fa-size="[200, 200]"
					> 

					<fa-modifier fa-align="[0,0]" fa-origin="[0.5,0.5]" fa-rotate="[0,rotY.get(),0]">

						<fa-surface fa-size="[undefined, undefined]" fa-background-color="'white'" ng-click="rotate()">
							<div  style="background:white;">Click Me</div>
							<img src="{{photo.row.images.thumbnail.url}}" width="200" height="200" />
						</fa-surface>

					</fa-modifier>

	</fa-modifier> 
```

Attached there is a picture of what the problem is:

![carrousel](https://cloud.githubusercontent.com/assets/3940503/4666924/01eb5ef8-5558-11e4-823a-8ea5c1ce32a2.jpg)

Thanks

**Comment by jordanpapaleo** [comment]
Hi @elinfante 

Is this still an issue or did @steveblue solution work?

Thanks,

Jordan

**Comment by jordanpapaleo** [comment]
I am going to close this.  Please reopen it if it is trill an issue.  Thanks - Jordan
