### ISSUE TITLE
fa-scroll-view doesn't appear to support 'true' sizing of elements

### ISSUE THREAD

**Issue by steveblue** [Famous/famous-angular#239]
famo.us 0.3.0 has the following in the changelog:
Scrollview can now handle "true" sized elements

Although this behavior doesn't seem to be working in famo.us / angular. When I set the size of sequenced `fa-view` encapsulating `fa-surface` to `[undefined,true]` the scrollview doesn't get the correct height and it collapses the fa-views on top of one another. When I give the views a height value that is a number the views are sequenced just fine.

Looking further into this, when the fa-size of a surface is modified with `true` the deployed surface doesn't have the 'height' set.

**Comment by steveblue** [comment]
I would think eliminating views from being sequenced inside a scrollview is an anti-pattern that doesn't allow elements to be ordered inside the scrollview. This is a severe handicap. We overcame this issue by implementing a service that calculates the size of the scroller. This should happen automagically.

**Comment by DSRoden** [comment]
Hi, I think I have a related issue and was hoping to get some clarity on what's going on here if anyone has a moment, thanks in advance. I'm using famo.us/angular for the first time, so sorry if the code is novice. 

The task: I am trying to implement an fa-scroll-view that repeats on an array of views. Each view has one image property and one text property. **not all images are the same size**

The problem: Images and text are rendered ok, but when scrolling to the bottom the surfaces can be scrolled completely out of view, and if they are they cannot be retrieved without a page refresh. I have tried to prevent this by giving fa-view that contains all the surfaces an fa-size. However, I'm finding it difficult to add a dynamic height value, one that will adjust to the size of the surfaces in the ng-repeat. Am I approaching this incorrectly. Can anyone suggest a way to prevent surfaces from scrolling out of view and becoming irretrievable? 

 fa-app(ng-controller='HomeCtrl')
    fa-scroll-view#main-scrollview(fa-pipe-from='myEventHandler' fa-options='options.container')
       fa-view(fa-size='[getPageWidth(), <how to get the height of all the surfaces dynamically?>])
           fa-modifier(ng-repeat='view in views track by $index' fa-size='[getPageWidth(), null]')
               fa-image-surface.relative-image(fa-image-url="{{view.image}}" fa-pipe-to='myEventHandler')
               fa-surface.relative-text(fa-size='[getPageWidth(), 100]' fa-pipe-to='myEventHandler')
                  .content(ng-if="view.text") {{view.text}}

Thanks again!
