### ISSUE TITLE
demos require a lot of scrolling to get from 1 page to the next

### ISSUE THREAD

**Issue by davis** [Famous/famous-angular#249]
On https://famo.us/integrations/angular/#/intro, I need to scroll at least 10 times in succession to get from 1 screen to the next. Is this intended?

I'm running latest Chrome on OS X Yosemite

Other than that, these examples are fantastic!!

**Comment by jordanpapaleo** [comment]
@davis I have noticed the same behavior with a mouse wheel scroll.  So its not just you.

**Comment by jordanpapaleo** [comment]
@davis Thank you for your support of this project.  Apparently this is how it was built.  I am going to close this as it it not an issue with famous-angular but with the decisions made building the website.  So in reality this would be a topic for the Famo.us team and up to them to work on the website.

Thanks again,

Jordan
