### ISSUE TITLE
Disabled button inside fa-surface still raise ngClick event

### ISSUE THREAD

**Issue by jbuiss0n** [Famous/famous-angular#261]
Hello,

I faced a strange issue, when a `<button>` is inside an `<fa-surafce>`, it always raise the ngClick event, even if the button is disabled usin ng-disabled.

Here is the guilty code:
```html
  <fa-modifier fa-size="[undefined, 40]" fa-origin="[.5, .5]" fa-align="[.5, 1]" fa-translate="[0, -30, 5]">
    <fa-modifier fa-size="[width - 2 * 20, 40]" fa-translate="[20, -50, 10]">
      <fa-surface class="capture">
        <button class="btn bg-grey-darken"
                ng-disabled="!isValid()"
                ng-click="goNextStep()" active-link>
          Click me
        </button>
      </fa-surface>
    </fa-modifier>
```

When `isValid()` returns false, button is clearly visible as disabled, but if you click on it, it still call the `goNextStep()` method.

**Comment by jordanpapaleo** [comment]
Hi @jbuiss0n -

Is this still a valid issue?  I just created a [codepen](http://codepen.io/anon/pen/MYJmGZ) for this and I am not able to reproduce the described behavior.  Maybe its already been fixed.  Can you please update the pen to a state where it is failing so I can better investigate your issue?

Thanks,

Jordan

**Comment by jbuiss0n** [comment]
Hello,

After some tests, it seems the bug was not really one... I think it's a misuse from us, we know only use `fa-click` on `fa-surface` (no button, or else) and everything looks good.

(I cannot see your codepen, it's blank for me).

Thanks for your help
