### ISSUE TITLE
Flexible Layout and fa-animate-leave

### ISSUE THREAD

**Issue by ghaiat** [Famous/famous-angular#268]
Hello

When a leaving a view containing  an fa-flexible-layout , i get an error from famous because it seems the nodes of the flexible layout are destroyed before the flexible-layout itself.

Here is a codepen to demonstrate the issue . 
I originally encountered the error when using fa-animate-leave but it seems to happen even without it .

here are 2 codepens , one without animation
http://jsfiddle.net/wnmodzs8

and one with 
http://jsfiddle.net/wnmodzs8/1/

Cheers

**Comment by jordanpapaleo** [comment]
Hi @ghaiat  - 

Is this still an issue?  If so could you please remake your examples off of this [codepen](http://codepen.io/zackbrown/pen/yyVQje).  You first example is not working.

Thanks,

Jordan

**Comment by jordanpapaleo** [comment]
I am going to close this.  Please reopen it if it is still an issue.  Thanks - Jordan
