### ISSUE TITLE
ng-model for surfaces and modifiers?

### ISSUE THREAD

**Issue by pencilcheck** [Famous/famous-angular#274]
It has always been this way, there is no way to handle custom html events on the surface because the scope is isolated (e.g. dragstart, etc) or do more advanced stuff with it like physics. I wonder if instead we can pass in surface reference via ng-model-ish directive as a workaround at the moment?

What I am envisioning is something like:

```html
<fa-surface ng-model="surfaceInstance"></fa-surface>
```

```javascript
var surfaceInstance = new Surface();
surfaceIntance.on('dragstart', function() {});
```

And for modifier, it would be nice especially for draggable, since I would like to attach certain event listeners or call specific function on it like 'activate', 'deactivate' but I can't because it is not exposed.

**Comment by jordanpapaleo** [comment]
Hi @pencilcheck 

Thanks for being a part of this project and your suggestions.  Unfortunately, this is not a task we are going to put additional energy into.  If it is something that you feel strongly about I would encourage you to make the changes and submit a pull request for it.

Thanks again,

Jordan
