### ISSUE TITLE
Angular compileProvider debug info

### ISSUE THREAD

**Issue by ghaiat** [Famous/famous-angular#283]
if you set  `$compileProvider.debugInfoEnabled(false)`in your app config, nothing shows up anymore.

FYI:
https://docs.angularjs.org/api/ng/provider/$compileProvider
You may want to disable this in production for a significant performance boost. See Disabling Debug Data for more.

**Comment by jordanpapaleo** [comment]
Hey @ghaiat 

Is there any additional thoughts on this?  Thanks - Jordan
