### ISSUE TITLE
No DrawerLayout directive

### ISSUE THREAD

**Issue by zablockijj** [Famous/famous-angular#296]
There is currently no directive to easily (via HTML) add a drawerlayout to the app.

**Comment by jordanpapaleo** [comment]
Hello - 

Thank you for the suggestion.  We will look at getting this on the roadmap for this project.

Thanks,

Jordan

**Comment by jordanpapaleo** [comment]
If you are interested I would recommend signing the CLA listed in the Contribution section of the docs, building the directive, and submitting PR.  I am not sure if or when this will be worked on.
