### ISSUE TITLE
fa-translate doesn't work with fa-scale

### ISSUE THREAD

**Issue by pencilcheck** [Famous/famous-angular#301]
https://famo.us/integrations/angular/docs/unstable/api/directive/faModifier/

Just go to any plunkr in this doc, and try to change fa-translate value while having fa-scale on, it doesn't work. Not only that, fa-scale doesn't work either.

**Comment by jordanpapaleo** [comment]
So there are 2 potential issues here.  

1. This is a documentation issue.  If you look in the famo.us code (src/core/Transform.js) you will see that the Transform.multiply function only allows 2 params so I dont think it is actually overriding but just not applying the other modifiers.  This means that you CANNOT mix and match all of these directives on you modifier.

Solution:
In this case what you would need to do is nest your transforms like this: Transform.multiply(skew, Transform.multiply(scale, translate));  This will need to occur in your controller and be applied using the fa-transform directive.  
![image](https://cloud.githubusercontent.com/assets/1728807/5649547/96c2765e-964b-11e4-888e-821d89befde4.png)

![image](https://cloud.githubusercontent.com/assets/1728807/5649534/828b60a6-964b-11e4-86d5-0ee1db383c68.png)
  I agree, that this may feel a little off but it works and you can do it right now.

2. The function in the famo.us core needs to be fixed.  I just created a fix for this and I will talk to the famo.us gate keeper this morning about it.  Hopefully it will be a good solution for them and pulled into the core.

**Comment by jordanpapaleo** [comment]
The famo.us core team changed this intentionally.  So as of now option one is the solution.  Can you please confirm that this works for you?

Thanks,

Jordan

**Comment by jordanpapaleo** [comment]
Good news.  I just spoke with Zack and we are going to implement this in famous-angular.  I will start working on this today.  Thank you for your patience on this and thank you for helping us up the quality of this project.

**Comment by jordanpapaleo** [comment]
https://github.com/Famous/famous-angular/pull/306
