### ISSUE TITLE
My app still does not scroll

### ISSUE THREAD

**Issue by udonline** [Famous/famous-angular#303]
I followed the documentation on 
famous-angular-starter-kit/famous-angular-0.3.0/docs/faq/index.html#basics-q4
and after commenting the line in the famous-global.js

// prevent scrolling via browser
window.addEventListener('touchmove', function(event) {
    event.preventDefault();
}, true);

My app does not still scroll

**Comment by jordanpapaleo** [comment]
Hi Udo - 

Can I please get a confirmation of this?  If not I will be closing this issue tomorrow.

Thanks,

Jordan
