### ISSUE TITLE
ng-click issues, conflict ? with famous angular

### ISSUE THREAD

**Issue by Christophe-Mercatante** [Famous/famous-angular#304]
Hi,
When I click on an element with a ng-click like this :

```
<p class="next" ng-if="step != steps.length-1" ng-click="nextStep($event)">
	<span ng-class="'icon-next'"></span>
</p>

<p class="reload" ng-if="step == steps.length-1" ng-click="nextStep($event)">
	<span ng-class="'icon-reload2'"></span>
	<span>Revoir le tutoriel</span>
</p>
```

My second p replaces the first one when step == steps.length-1 but unfortunately the nextStep is recall even if I have not click on because the two elements have the same position (graphically).

This is what I got in my console :

jQuery.Event {originalEvent: CustomEvent, type: "click", isDefaultPrevented: function, timeStamp: 1420470018176, jQuery213026396643021143973: true…}

jQuery.Event {originalEvent: MouseEvent, type: "click", isDefaultPrevented: function, timeStamp: 1420470018217, jQuery213026396643021143973: true…}

The additional event "MouseEvent" seems to be fired by famous angular. I just want the CustomEvent fired by ng-click. What can I do ?

Thanks in advance.

Christophe M

**Comment by Christophe-Mercatante** [comment]
Hi Jordan,

This is my updated codepen : http://codepen.io/anon/pen/qEREvw
To reproduce issue, you have to toggle to device mode on chrome to simulate touch event.

As you can see, you can not access to step4.
Between step1 -> step2,  step2 -> step3, a custom event is fired. But between  step3 -> step4 a custom event is followed by a mouse event and directly we go back to  step4 -> step1.

I hope that you have an idea about it.
Thanks in advance.

Christophe

**Comment by jordanpapaleo** [comment]
Hi Christophe - 

I tried it with ng-show instead of ng-if and there are not any errors.  Take a look at this [stackoverflow post](http://stackoverflow.com/questions/21869283/when-to-favor-ng-if-vs-ng-show-ng-hide).  Are you able to use ng-show in this case?  

Thanks,

Jordan

**Comment by Christophe-Mercatante** [comment]
Hi Jordan,

I have updated the codepen : http://codepen.io/anon/pen/qEREvw with ng-show and it doesn't change anything. In that case,  I can not access to the step4.

Christophe

**Comment by jordanpapaleo** [comment]
Hi Christophe -

Thank you for your patience with this.  Your codepen is working for me.  So lets start over to make sure I am not missing something. I start on step1 and click bringing me to step 2, then 3, then 4 where the markup is toggled to the reload class markup.  Clicking in the reload markup should start the process over again.  I can do all of that without any errors.  What browser/operating system are you using?

I will dig deeper into code base investigating the additional mouse event you mentioned.

Talk soon,

Jordan

**Comment by jordanpapaleo** [comment]
Also what version of famous-angular are you using?

**Comment by Christophe-Mercatante** [comment]
To reproduce issue, you have to toggle to device mode on chrome to simulate touch event. (key F12)
Have you thought about it ?

**Comment by jordanpapaleo** [comment]
Yup, I am in device mode.

**Comment by jordanpapaleo** [comment]
![image](https://cloud.githubusercontent.com/assets/1728807/5666500/dab8ded8-9714-11e4-9fcb-245afbd5ae79.png)
Is it a certain device that you are using?

**Comment by Christophe-Mercatante** [comment]
You also have to activate "emulate touch screen" into "drawer" => "Emulation".
With this configuration, you will see what's happening to a mobile, and what events are fired into the console.

**Comment by jordanpapaleo** [comment]
Hi - 

So the more I played with this the more it seemed like an angular implementation issue instead of a famous-angular issue.  Check out this [pen](http://codepen.io/anon/pen/GgryxK?editors=101) and let me know if it works for you.

**Comment by jordanpapaleo** [comment]
I am going to close this.  Please reopen it if it is still an issue.  Thanks - Jordan

**Comment by Christophe-Mercatante** [comment]
Hi Jordan,

I just made an other code pen with only angularJS and not famous-angular and my example works perfectly without famous-angular.

The issue occurs when you use ng-click on html elements and the touch events.

This is the other code pen : http://codepen.io/Titoph/pen/jEmrzX

Thanks

**Comment by Christophe-Mercatante** [comment]
I don't how to reopen the issue....

**Comment by jordanpapaleo** [comment]
Thanks for the second pen

**Comment by jordanpapaleo** [comment]
Hi @Christophe-Mercatante -

This is actually an issue with famo.us.  I have discovered the problem and figured out a solution.  I will get a PR in soon.  I am not sure of when that will be merged into Famo.us though.  I will post my branch with the solution so you can see the fix and then make the change in your famous-global.js if you want.  Sorry this took so long.  I do appreciate your patience.

Jordan

**Comment by jordanpapaleo** [comment]
Fix in PR https://github.com/Famous/famous/pull/586
