### ISSUE TITLE
zIndex Firefox

### ISSUE THREAD

**Issue by zoneblaze** [Famous/famous-angular#307]
I am not having any luck with the zIndex property in Firefox on a desktop set up.

```<fa-surface ng-if="bubble.ondisplay" fa-properties="{zIndex: '{{bubble.zindex}}'}">```

Any other browser sets it to the correct value, e.g. in my set up, bubble.zindex = 1 to 5, tested in Chrome, Safari, Opera, IE. But Firefox always sets all instances to zIndex:0. Am I missing a trick or is that a specific Firefox bug?

**Comment by jordanpapaleo** [comment]
Hi @zoneblaze 

Please create a [codepen](http://codepen.io/zackbrown/pen/yyVQje) so we can better see what you are doing.

Thanks,

Jordan

**Comment by zoneblaze** [comment]
Ok, just done a very simple example here:
http://codepen.io/anon/pen/QwdgGo

Duplicated the famous logo view and added fa-properties zIndex:1 to the first logo and zIndex:2 to the second one.

Then inspect element on the two logos, in all browsers their zindex will come up as 1 and 2 as expected, except Firefox, sets it as 0 for me.

![zindex0](https://cloud.githubusercontent.com/assets/684079/5669493/d02c6312-976f-11e4-89db-045df0bfee68.gif)

**Comment by jordanpapaleo** [comment]
Thanks. I see the issue and will look into it.

**Comment by jordanpapaleo** [comment]
This is a bug in famo.us core.  I am getting a PR in for it now.  The fix I am submitting will remove firefox specific code from for z-index from famous-global.js.

![image](https://cloud.githubusercontent.com/assets/1728807/5672903/2f1b3e32-974a-11e4-9a22-4fa711324434.png)

You can do this right now in your famous-global.js file to get it working until it is has been merged into and released.

**Comment by jordanpapaleo** [comment]
I am closing this as it is a Famo.us issue.  I submitted a [PR](https://github.com/Famous/famous/pull/568) to fix it.

**Comment by zoneblaze** [comment]
Cool thanks!
