### ISSUE TITLE
fa-draggable doesn't work with fa-options

### ISSUE THREAD

**Issue by leestar** [Famous/famous-angular#308]
fa-draggable doesn't seem to work when assigning options via fa-options.

See the following codepen:

http://codepen.io/anon/pen/GgrMzv

**Comment by SuPenguin** [comment]
Hi,
It works without scale. This is a famo.us issue, it tries to set the scale options before the MouseSync is created. But i've created a pull request to correct this : https://github.com/Famous/famous/pull/569.

**Comment by jordanpapaleo** [comment]
Great work @SuPenguin.  I am closing the as it is a Famo.us issue not a famous-anguar one.  Thank you @leestar for using famous-angular.
