### ISSUE TITLE
Trying to trigger touch events inside a suface after using fa-pipe-to

### ISSUE THREAD

**Issue by koflaherty** [Famous/famous-angular#315]
I'm using an fa-pipe-to on a surface to send events to a Famo.us eventHandler for detecting events, however, using fa-pipe-to stops touch events from reaching the HTML elements inside the surface with the fa-pipe-to attribute. Is this a bug, or is there a common design pattern or work around for this?

**Comment by jordanpapaleo** [comment]
Hi @koflaherty -

Can you please create a [codepen](http://codepen.io/zackbrown/pen/yyVQje) to show me your issue?

Thanks,

Jordan

**Comment by koflaherty** [comment]
Hi Jordan. I couldn't replicate the error. We're currently migrating a prototype from the Ionic Framework to Famo.us. There might be something in Ionic that is stopping the event propagation. I'll just have to rip out Ionic completely and see if that does the trick.

What didn't work on my code base but does on CodePen: http://codepen.io/anon/pen/OPpqeB

**Comment by koflaherty** [comment]
Yep removing Ionic Angular did the trick! Must be something in there that stopped the events.

**Comment by jordanpapaleo** [comment]
Thats great to hear.  We are all pumped to see people moving to Famo.us.  Thanks for your support. - Jordan
