### ISSUE TITLE
fa-image-surface and fa-surface doesnt translate

### ISSUE THREAD

**Issue by benag** [Famous/famous-angular#316]
I was workign with fa-surface fine but once i changes to fa-image-surface it stops translating to tha same place:

<fa-modifier fa-size="[200*model.normal, 200*model.normal]" 
  fa-translate="myTrans.get()">
            <fa-surface fa-background-color="'orange'" fa-color="'white'" fa-click="animate('1')"  ><span style="font-size: 25px;"></span></fa-surface>
</fa-modifier>

<fa-modifier fa-size="[200*model.normal, 200*model.normal]" 
 fa-translate="myTrans.get()">
       <fa-image-surface fa-image-url="images/circlepseefas.jpg" fa-click="animate('1')" >
            </fa-image-surface>
          </fa-modifier>

$scope.myTrans = new Transitionable([0, 0, 0]);

**Comment by jordanpapaleo** [comment]
Hi @benag -

Please create a [codepen](http://codepen.io/zackbrown/pen/yyVQje) so we can take a look at your code.

Thanks,

Jordan
