### ISSUE TITLE
Center Text Inside fa-surface

### ISSUE THREAD

**Issue by groupsvkg** [Famous/famous-angular#317]
Hi Team,

How can i center a Text inside fa-surface?

Regards,
vishal

**Comment by steveblue** [comment]
@groupsvkg If the surface only contains a block of text, you can use fa-origin and fa-align to center the surface, not the text. Surfaces are components of a View or Layout, it is not always the best option to treat a surface like a view onto itself. This would be your best option, as the options to align elements vertically with CSS alone is rather limited.

**Comment by jordanpapaleo** [comment]
Also remember to use the CSS property text-align: center for your content you want horizontally centered inside of a surface.
