### ISSUE TITLE
Documentation Header issue(http://famo.us/integrations/angular/docs/api/)

### ISSUE THREAD

**Issue by groupsvkg** [Famous/famous-angular#321]
Hi Team,

i am using chrome 39.0.2171.71 (64-bit) to read famous-angular document(http://famo.us/integrations/angular/docs/api/). Header is overlapping links.

Regards,
vishal
![famous-angular-doc](https://cloud.githubusercontent.com/assets/366335/5839797/b27155c0-a1b6-11e4-8c87-f15d35eeee6d.png)

**Comment by jordanpapaleo** [comment]
Hi @groupsvkg - 

Thanks for finding this.  This is an issue with the Famo.us website not Famous-angular.  I will pass this on to the appropriate people.

Thank you,

Jordan
