### ISSUE TITLE
Scrollview's setPosition() and setVelocity() doesn't always work when at the top or bottom of a scroll view

### ISSUE THREAD

**Issue by koflaherty** [Famous/famous-angular#332]
When a scrollview is on the edge of its content, the top or bottom of the scroll view, the setPosition() or setVelocity() functions won't perform correctly if the previous scroll direction was opposite to that of the new scroll direction.

I've made the following codepen to show the issue. http://codepen.io/anon/pen/yyoodN

Basically I'm trying to program a scroll to bottom, or lock to bottom with new content coming into the scroll view.

**Comment by jordanpapaleo** [comment]
Hi @koflaherty  -

So this is actually a issue with Famo.us not Famous-Angular.  I would encourage you to open an issue with with [Famo.us](https://github.com/Famous/famous/issues).

Thanks,

Jordan
