### ISSUE TITLE
Feature request: Better support for child ui-view

### ISSUE THREAD

**Issue by steveblue** [Famous/famous-angular#335]
I have a feature request. This already works but with mixed results. This div gets transcluded by ui-router and then inserts various templates per child route we set. Problems with this method started appearing around ~0.5 / famo.us 0.3. It seems to happen randomly, but some scrollviews inside the child end up getting their _node set to null. Maybe it's also because we're trying to display almost a dozen horizontal scrollviews in our layouts, who knows?

```
    <fa-scroll-view>
      <div ui-view id="child-view"></div>
    </fa-scroll-view>

```

**Comment by jd-carroll** [comment]
:+1:

Might it be easier to support through a custom `<fa-ui-view id=" ">` tag?

**Comment by steveblue** [comment]
At first it seemed like th UI-view was to blame but now I don't think it is. I ended up converting a bunch of scrollviews to sequentialLayouts and now move them with a GenericSync scoped to each component. This approach seems to be way more peformant and is less prone to issues.

**Comment by jd-carroll** [comment]
@steveblue It sounds like the issue really isn't resolved though and this would be a nice feature to have.  Could you re-open this issue otherwise I'll create a separate for the same thing.
