### ISSUE TITLE
Way to allow native scrolling for certain elements/areas?

### ISSUE THREAD

**Issue by 5inline** [Famous/famous-angular#339]
Is there a way to disable the Famo.us override of all touch events for specific elements?

For example, I have an image displayed that is larger than the container element with an overflow:scroll parameter. I want to be able to pan the image within the container element, and using the native functionality would be much easier to rolling my own event handler.

**Comment by jd-carroll** [comment]
No there is not, but it should be pretty easy to add only a single element to a Scrollview.

**Comment by 5inline** [comment]
That would only scroll in one direction, correct?

I'm browsing the source code, and don't see an obvious way to allow scrolling in both horizontal and vertical.

**Comment by jd-carroll** [comment]
The current scroll-view will only move in one direction at a time, correct.
