### ISSUE TITLE
Problems with ng-repeat in Layout

### ISSUE THREAD

**Issue by janober** [Famous/famous-angular#342]
I wanted to make the content in a Sequential-Layout (or other similars) sortable. However I am totally unable to get it working. Somehow the data does not update correctly.

I created that simple codepen to demonstrate:
http://codepen.io/anon/pen/EaQbxy

When the button "move down" gets pressed the entry should simply move down one position. But that does not work when I have the ng-repeat on the modifier. However works totally fine when I do it on a div (code is also in there, can simply get uncommented and the famous-angular one commented out).

Thanks!

**Comment by atgillette** [comment]
I've seen the same issue with fa-grid-layout, http://plnkr.co/edit/TGQqurdw5ZJbwlRRUaGE?p=preview.

**Comment by atgillette** [comment]
I came across a fix to this issue #293 using fa-index and have updated the plnkr example.

**Comment by janober** [comment]
Great to hear that you found a solution & thanks for posting it!

However just tried if that also works for my issue but it does sadly not.

**Comment by zackbrown** [comment]
Hey @janober , I agree that this sounds like an issue that could be solved with fa-index--it sounds like something else may be going on, though. Without more detail, it's difficult to offer support. Can you create a codepen that reproduces the error you're encountering?

**Comment by janober** [comment]
Hello @zackbrown , there is already a code pen which shows my issue. It is above in my original issue. However forked it and added the fa-index. That version can be found here:
http://codepen.io/anon/pen/qEoYZY

Thanks!

**Comment by zackbrown** [comment]
It was a bug in fa-sequential-layout. (the 'update' function was not specified for fa-sequential-layout like it should be, and as it is with fa-grid-layout, fa-scroll-view, etc.)   I updated your codepen with a build of master and now it works as expected.  See http://codepen.io/zackbrown/pen/RNMzOB . The commit for this fix is 25dd0403f5e37dd4906ed4e371f15228fc341504 .

**Comment by janober** [comment]
Great Zack! And Thanks a lot like always. Works now perfectly like you said.

Closing...
