### ISSUE TITLE
famous-angular with requirejs can't find famous

### ISSUE THREAD

**Issue by systembugtj** [Famous/famous-angular#343]
I use the famous-angular with requirejs with below config.  Also I try the famous.js not the global one, still not working, always got angular exception famous is undefined. 

So I need to include the famous.js in <head> to allow it work. I'm not very familiar with famous, is there a way to put famous-angular work with requirejs?

paths: {
        'famous' : 'vendor/famous/dist/famous-global',
        'famous-angular' : 'vendor/famous-angular/dist/famous-angular',
},
shim : {
       'famous' : {
            exports : 'famous'  
        },
        'famous-angular' : {
            deps: ['angular', 'famous'],
        },
},

**Comment by jd-carroll** [comment]
I think the more important question is how are you planning to use requirejs with angular?

Not that it's impossible, but if you are just beginning, you are going about it **way** wrong.  Take a look at the [famous-angular-examples](https://github.com/thomasstreet/famous-angular-examples) and build from there.

**Comment by jordanpapaleo** [comment]
Hi - 

We do not support RequireJS and personally I would not implement famous-angular that way.  The closest you will probably get for support on this topic is confirming what files should be used.  You need [angular.js](//ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.js), [famous-global.js](//code.famo.us/famous/0.3.4/famous-global.js), and [famous-angular.js](//code.famo.us/famous-angular/0.6.0/famous-angular.js)  Take a look at this [CodePen](http://codepen.io/zackbrown/pen/yyVQje) if you need an example of a working app.  

Thanks,

Jordan

**Comment by steveblue** [comment]
@systembugtj I disagree with @jordanpapaleo. We use Angular very successfully with require.js and wrap every module we create in a define function so we can inject external dependencies into our directives, services, providers, that is for everything except for famous. With famous/angular, we reference all famo.us methods using the included $famous provider.  For a great tutorial on how to structure an Angular app with Require, visit http://solutionoptimist.com/2013/09/30/requirejs-angularjs-dependency-injection/

**Comment by matt-d-rat** [comment]
@steveblue we use a similar method to the one you have described. +1 for releasing a boilerplate though, then we have the best of both worlds.

**Comment by steveblue** [comment]
@matt-d-rat i've gone ahead and made a famous angular boilerplate that uses require for external dependency injection available on github. This boilerplate takes a lot of ideas from Thomas Burleson and maintains a clearly readable folder structure. I've also included a small library for handling responsive within a web app, with breakpoints mirrored in SASS. At some point, I'll add support for Grunt (as it only builds with Gulp currently), LESS and a few other options. If anyone wants to contribute to the project, just contact me. https://github.com/steveblue/fa-boilerplate

**Comment by ThomasHambach** [comment]
For those of you still looking for the issue. You can just solve it by including famous-global.js somewhere in your HTML.
