### ISSUE TITLE
fa-attribute on fa-container-surface

### ISSUE THREAD

**Issue by bthj** [Famous/famous-angular#344]
`fa-container-surface` doesn't seem to accept an `fa-perspective` attribute.  That would be useful as container surfaces have their own isolated rendering environment.

Nesting a modifier inside the `fa-container-surface` element doesn't have an effect, like so:
```html
    <fa-container-surface fa-options="..." id="items-container">
      <fa-modifier fa-perspective="1000">
        ...
      </fa-modifier>
    </fa-container-surface>
```

But I was able to achieve the desired perspective within the container surface, by writing the following in the controller, which is less declarative:
```javascript
      var containerSurface = $famous.find('#items-container')[0];
      containerSurface.renderNode.context.setPerspective(1000);
```

**Comment by jordanpapaleo** [comment]
Hi @bthj  - 

Thanks for using Famous-Angular.  I am not sure what would be the resolution for this issue would be.  It seems that you found a need and filled.  As this is an open source project I would encourage you to put this into a directive, write some test, and then submit a PR for the project.

Thanks,

Jordan

**Comment by steveblue** [comment]
@bthj you can do the following which I think is perfectly acceptable. 

```
JS:
                  var group = $famous.find('.container-class')[0].renderNode._container;
                  group.classList.add('depth');

```
```
CSS
    .depth{
      -webkit-perspective: 1000px;
       perspective:1000px;
    }
```
