### ISSUE TITLE
Setting fa-size="[true, true]" on modifier causes it to ignore fa-origin="[0.5, 0,5]"

### ISSUE THREAD

**Issue by atgillette** [Famous/famous-angular#346]
I encountered a similar issue to #240 when you set fa-size="[true, true]" on a parent modifier.  Although I worked around this by placing fa-size on the fa-surface node, it's my understanding that size should defined at the modifier level.   Can someone explain why this is breaking?

**Comment by jordanpapaleo** [comment]
Hi - 

You are correct about the proper place for fa-size; it should be on the modifier.  True sizing has been a point of confusion as it was never really implemented.  If you look through the issues, you will see a handful of fa-size issues for true sizing.  You will need to follow the solution in [240](https://github.com/Famous/famous-angular/issues/240) If you want this to work.  Hopefully future versions will have this worked out.  I imagine this is not the exact answer your are looking for but it is the only one I have.  Thanks for using and supporting this project.

Jordan
