### ISSUE TITLE
footer does not show in "fa-header-footer-layout"!

### ISSUE THREAD

**Issue by train860** [Famous/famous-angular#353]
Hi,can you help! Thanks
here is my code.but the footer did not show in my phone.
![037c0ade-2876-4c41-bf22-b62cb566ddbf](https://cloud.githubusercontent.com/assets/6874537/6827009/0576f9f4-d340-11e4-90e2-7ac2bba5ad73.png)

**Comment by OddNaughty** [comment]
Got the same here.
There's a codepen:
http://codepen.io/OddNaughty/pen/pJzozP

**Comment by zackbrown** [comment]
The two of you are running into different issues:

@train860 , you need to specify the headerSize and footerSize in the options for fa-header-footer-layout (see the code in @OddNaughty 's CodePen.)

@OddNaughty , as mentioned in the readme you need to specify a height for your fa-app.  See this modified codepen:  http://codepen.io/zackbrown/pen/YXKrRR

**Comment by OddNaughty** [comment]
Oh yes, my bad ! Thank you @zackbrown !

**Comment by train860** [comment]
Thank you ！！！
