### ISSUE TITLE
fa-scroll-view resize not working as expected

### ISSUE THREAD

**Issue by dx9** [Famous/famous-angular#361]
Not sure the setup is correct. 

When you resize the scroll view gets confused. It will under/over scroll based on a smaller/larger resize condition.

http://codepen.io/anon/pen/yymqap?editors=101

**Comment by steveblue** [comment]
true sizing inside a Scrollview is not supported in famous-angular I do not believe. you probably have to update the size of the Scrollview on resize.

**Comment by dx9** [comment]
Steve thanks for the heads up.

Played with this and it looks like Surfaces with a size of [undefined,true] or [true,undefined] don't detect the 'resize' size change which causes ScrollView.ViewSequence.Backing.calculateSize() to recalc the incorrect size.

Tweaked Surface to detect the size change under these conditions which makes ScrollView work better in this situation. Looking at getting ScrollView to reposition Scroller based on resize of it's ViewSequence.Backing. Might work then, not sure if any of this is naughty or nice. 

I guess though not really a famous-angular issue. I'll start one up over in famous land.
