### ISSUE TITLE
faScrollView disapears when paginated = true on dragging (not mouse scrolling)

### ISSUE THREAD

**Issue by lucasbeef** [Famous/famous-angular#379]
I used the famous-angular-starter and copy/pasted exactly the third example given at http://famo.us/integrations/angular/docs/unstable/api/directive/faScrollView/index.html 

It's an horizontal scrollView with pagination. Here : http://plnkr.co/edit/90BkpMGb7oU0fe85T305

When testing it on mobile (but the same problem occurs on Chrome dev mode as well) when I touch and drag to the left, the entire scrollView disappears from the screen. This occurs only when paginated = true and only when dragging from right to left. No problem with the mouse scroll either, it works in both directions.

The example worked on 0.3.0, but not on 0.5.0

(Side question : How can I get the index of the current page ?)

**Comment by steveblue** [comment]
@lucasbeef Famous/Angular doesn't support Mixed Mode (0.5+) and hasn't been actively developed since March. The Scrollview was notoriously buggy in this implementation.

**Comment by lucasbeef** [comment]
@steveblue thanks. So i guess I should try the new famous framework instead of famous-angular ?

**Comment by steveblue** [comment]
@lucasbeef you can loosely couple angular 1.4 with famous 0.5+, meaning create directives that generate Famo.us DOMElement and Mesh using straight up Javascript with little to no support for templates. I started development on an integration between Mixed Mode and Angular 2 but it is still very early on and Angular 2.0 isn't stable. https://github.com/steveblue/ngus

**Comment by lucasbeef** [comment]
@steveblue Thanks, im gonna follow your work, but i wanna wait to make the switch to Angular 2. In the meantime i'll just do that.
