### ISSUE TITLE
Famo.us + Angular2? How hard is it?

### ISSUE THREAD

**Issue by xdemocle** [Famous/famous-angular#380]
Hi guys, i'm starting a new startup mobile app and I would like to mix Angular2 with Famo.us for UI animation and effects.

Do you think is too difficult make this step at moment?
Since officially the current integration support only AngularJS 1?

Thanks in advance, cheers

**Comment by steveblue** [comment]
I have started a project here @xdemocle https://github.com/steveblue/ngus

**Comment by xdemocle** [comment]
Brilliant, I'll take a look asap.
Maybe I could be able to collaborate with you.
Cheers,

Rocco R.
(message sent from smartphone, please excuse my typos)

**Comment by steveblue** [comment]
@xdemocle we're looking for contributors to the project for sure.
