### ISSUE TITLE
[ng:btstrpd] App Already Bootstrapped 

### ISSUE THREAD

**Issue by stukennedy** [Famous/famous-angular#51]
I'm getting the following error when running my F/A app

```
Uncaught Error: [ng:btstrpd] App Already Bootstrapped with this Element '<html ng-app="integrationApp" data-ember-extension="1" class="ng-scope">'
```

The issue doesn't stop the app from working, it's just concerning ... it seems to think I've assigned `ng-app` twice. 
I've only added it in the index.html

```
<html ng-app="integrationApp">
```

**Comment by zealmurapa** [comment]
in response to this issue: if you really haven't called it twice, the issue might be that you are using another framework that uses its own embeded Angularjs, and you have gone on to install engularjs on top of that
