### ISSUE TITLE
Initial Bootstrapping of Require + Famous not performant for deployment

### ISSUE THREAD

**Issue by MylesBorins** [Famous/famous-angular#57]
Require.js is usually used only in development.  For production almond + r.js is usually used to create a minified source for the entire application.  This workflow does not make a ton of sense for an angular application though, and trying to support require may "over time" lead to problems.

Internally we have discussed making a single file famous.min.js that has a global object that has keys associated with each of the modules offered.  So something like Famous["core/Context"] will return the context object... this is pretty much the exact same pattern you guys are already using

Once this version of famous.min.js is available I think moving forward should be rather painless!

**Comment by Braintelligence** [comment]
So is this being continued?

**Comment by zackbrown** [comment]
This original issue was resolved when the global build of Famo.us became available about six months ago.

**Comment by Braintelligence** [comment]
I see. I'm new to famo.us and am trying to find out how to run famo.us with local libs. While trying to solve the famo.us academy challenges I encounter errors when trying to use my local libs though, especially the Engine.js.
So I was wondering what I'm doing wrong.

Sadly, idling for half a day waiting for a response in the IRC channel didn't help =(.

**Comment by TheAlphaNerd** [comment]
@braintelligence

sorry you have had so much trouble.  I’ll be idling on irc from 10 am - noon pst tomorrow… ping me=

**Comment by Braintelligence** [comment]
@TheAlphaNerd Thank you very much for your offer. I'll try to be there, this will be 7pm CET for me. See you then!

**Comment by Braintelligence** [comment]
@TheAlphaNerd I'm there, what is your nickname in IRC so I can ping you?

**Comment by TheAlphaNerd** [comment]
I'm thealphanerd on irc as well. Still on Route. Should be there by 10:30

**Comment by Braintelligence** [comment]
Roger. See you then :).
